# Build stage  
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build  
WORKDIR /src  
  
COPY *.csproj ./  
RUN dotnet restore  
  
COPY ./ ./  
RUN dotnet publish -c Release -o /app/publish  
  
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime  
WORKDIR /app  
VOLUME ["/app/data"]  
ENV TZ=Europe/Moscow  
ENTRYPOINT ["dotnet", "VolleyballBot.dll"] 
